apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "capacitor-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "capacitor-agent.labels" . | nindent 4 }}
    {{- with .Values.configmapLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.configmapAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- toYaml .Values.env | nindent 2 }}
