apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "capacitor-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "capacitor-agent.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.env | nindent 2 }}
