apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "capacitor-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "capacitor-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "capacitor-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "capacitor-agent.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "capacitor-agent.serviceAccountName" . }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        {{- with .Values.securityContext.pod }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            {{- with .Values.securityContext.container }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          envFrom:
            {{- if .Values.existingSecret.name }}
            - secretRef:
                name: {{ .Values.existingSecret.name }}
            {{- end }}
            - secretRef:
                name: {{ include "capacitor-agent.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

