apiVersion: v2
name: capacitor-next-agent
description: A Helm chart for Capacitor Next Agent - Remote cluster agent for Capacitor
type: application
version: 0.12.0-rc.4
appVersion: "agent-0.12.0-rc.4"
home: https://github.com/gimlet-io/capacitor
maintainers:
  - name: Gimlet
    email: laszlo@gimlet.io
keywords:
  - kubernetes
  - fluxcd
  - agent
  - remote-cluster
sources:
  - https://github.com/gimlet-io/capacitor

