apiVersion: v2
name: capacitor-next
description: A Helm chart for Capacitor Next - Kubernetes UI for FluxCD
type: application
version: 2025-10.2-rc6-1-g7a90155
appVersion: "v2025-10.2-rc6-1-g7a90155"
home: https://github.com/gimlet-io/capacitor
maintainers:
  - name: Gimlet
    email: laszlo@gimlet.io
keywords:
  - kubernetes
  - fluxcd
  - ui
  - gitops
sources:
  - https://github.com/gimlet-io/capacitor

