apiVersion: v2
name: capacitor-server
description: A Helm chart for Capacitor Next - Kubernetes UI for FluxCD
type: application
version: 0.1.0
appVersion: "v2025-10.1"
home: https://github.com/gimlet-io/capacitor
maintainers:
  - name: Gimlet
    email: laszlo@gimlet.io
keywords:
  - kubernetes
  - fluxcd
  - ui
  - gitops
sources:
  - https://github.com/gimlet-io/capacitor

