name: üöÄ Publish

on:
  push:
    tags:
      - 'capacitor-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating the GitHub release
      packages: write # Required for pushing to GitHub Container Registry
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
    - name: üõë Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.0
    - name: ‚¨áÔ∏è Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 5
    - name: Version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]
        then
            tag=${GITHUB_REF##refs/tags/}
            v=${tag##capacitor-}
            echo "::set-output name=version::$v"
        else
            echo "::set-output name=version::$GITHUB_SHA"
        fi
    - name: üèóÔ∏è Build UI
      run: make build-ui
    - name: Dist
      run: make dist
      env:
        VERSION: ${{ steps.version.outputs.version }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Capacitor ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.2.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.10.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }} # `PAT` is a secret that contains your Personal Access Token with `write:packages` scope
    - name: Build and push Gimlet image
      id: build-and-push
      uses: docker/build-push-action@v4.2.1
      with:
        context: .
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: |
          ghcr.io/gimlet-io/capacitor:${{ steps.version.outputs.version }}
    - name: Set up Flux CLI
      uses: fluxcd/flux2/action@v2.2.3
    - name: Push manifests
      run: |
        flux push artifact \
        oci://ghcr.io/gimlet-io/capacitor-manifests:${{ steps.version.outputs.version }} \
        --path=deploy/k8s \
        --source=${{ github.repositoryUrl }} \
        --revision="${{ github.ref_name }}@sha1:${{ github.sha }}" \
        --annotations='org.opencontainers.image.description=Capacitor install manifests for Flux'
    - name: Install cosign
      uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 #v3.1.1
      with:
        cosign-release: 'v2.1.1'
    - name: Sign oci artifacts
      run: |
        # keyless mode
        cosign sign ghcr.io/gimlet-io/capacitor-manifests:${{ steps.version.outputs.version }} -y
